### ISSUE TITLE
Making it easier for ld to find this library

### ISSUE THREAD

**Issue by yceh** [websnarf/bstrlib#17]
Is it possible to rename bstrlib as libbstr? Or I should name the shared library as libbstrlib.so ?
I am packaging bstrlib as a shared library on Fedora, a linux distribution. I named the shared library libbstr.so,so it can be found easily be ld, but this introduce some unnecessary confusion. I have added a pkg-config file as a workaround.

**Comment by denisdemaisbr** [comment]
Hi a classic example is zlib

files:
static lib: libz.a
shared lib: libz.so (-lz)

tryout $man ld
